AppBundle\Entity\Events:
    type: entity
    table: events
    repositoryClass: AppBundle\Entity\EventsRepository
    indexes:
        FK_events_room:
            columns:
                - room
        FK_events_user:
            columns:
                - userid
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tmin:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
        tmax:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
        hmin:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
        co2max:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
        vocmax:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
        description:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
    manyToOne:
        room:
            targetEntity: Rooms
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                room:
                    referencedColumnName: id
            orphanRemoval: false
        userid:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                userid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
