AppBundle\Entity\Thtable:
    type: entity
    table: thtable
    repositoryClass: AppBundle\Entity\ThtableRepository
    indexes:
        ix_room_time:
            columns:
                - room
                - date
        IDX_51E7DE2A729F519B:
            columns:
                - room
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: datetime
            nullable: false
        co2:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        t:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        h:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        voc:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        vocr:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        vocold:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
    manyToOne:
        room:
            targetEntity: Rooms
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                room:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
