AppBundle\Entity\Users1:
    type: entity
    table: users1
    uniqueConstraints:
        ix_uid:
            columns:
                - uid
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
