<?php

namespace AppBundle\Entity;

/**
 * HistoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriesRepository extends \Doctrine\ORM\EntityRepository {

    public function addHisEvent(\AppBundle\Entity\Events $e) {
        $h=new Histories();
        $h->setEv($e);
        $em=$this->getEntityManager();
        $em->persist($h);
        $em->flush();
    }

}
