<?php

namespace AppBundle\Entity;

/**
 * RoomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomsRepository extends \Doctrine\ORM\EntityRepository
{
public function PrepareRooms($rooms){
    $arr=[];
    /* @var $room \AppBundle\Entity\Rooms */
    foreach($rooms as $room){
        $arr[$room->getId()]=$room->getName();
    }
    return $arr;
}


}
